name: Unit Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm test